### PR TITLE
[WFCORE-5147] Adjusting git integration logging and stability of RemoteSshGitRepositoryTestCase

### PR DESCRIPTION
**Pull request by darranl**
I have also submitted a PR to WildFly Core as the changes are generic enough and may be useful to support the feature https://github.com/wildfly/wildfly-core/pull/4352

### CODE REVIEW

**Comment by darranl** [comment]
I am going to need to recreate this PR, I have ended up with a Temp commit that should have been combined with another creeping in.

**Comment by darranl** [comment]
Done

**Comment by kabir** [comment]
@darranl I recently rebased my gh-action-fixes branch and may have made other changes before that. Can you rebase/cherry-pick? Since I see some of my commits in here (as well as the temp commit you mention)

**Comment by darranl** [comment]
@kabir this should be ready now

**Pull request merged**
